apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: LoadBalancer
  selector:
    app: moonlink-deployment
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
