apiVersion: apps/v1
kind: Deployment
metadata:
  name: moonlink-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moonlink-deployment
  template:
    metadata:
      labels:
        app: moonlink-deployment
    spec:
      containers:
      # Moonlink deployment, which serves REST API and TCP rpc requests.
      - name: moonlink-deployment
        image: us-west1-docker.pkg.dev/coral-ring-465417-r0/moonlink-standalone-experiment/moonlink-deployment:42f29a70-e2f2-4ac2-99f8-95f830464ecc
        command: ["/app/moonlink_service"]
        args:
        - "/tmp/moonlink"
        - "--no-rest-api"
        - "--tcp-port=3031"
        env:
        volumeMounts:
        - name: shared-cache-directory
          mountPath: /tmp/moonlink
        ports:
        # Port number for REST API server.
        - containerPort: 3030
        # Port number for TCP rpc server.
        - containerPort: 3031

      # Data server, which serves data plane requests.
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        # nginx serves local files under certain directory.
        - name: shared-cache-directory
          mountPath: /usr/share/nginx/html

      # TODO(hjiang): Currently serves merely as source database to sync from, need to remove before release.
      - name: postgres
        image: mooncakelabs/pg_mooncake
        env:
        - name: POSTGRES_PASSWORD
          value: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data

      volumes:
      - name: pgdata
        emptyDir: {}
      # Shared cache directory between data server and moonlink.
      - name: shared-cache-directory
        emptyDir: {}
